services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 8080:80
    volumes:
      - ./data/files:/data/files

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - mongo
    environment:
      - HTTPS_PROXY
      - EMAIL_PASSWORD
      - JWT_SECRET
      - PIXIV_COOKIE_PHPSESSID
      - MONGODB_URL=mongodb://mongo:27017
    volumes:
      - ./data/files:/data/files

  mongo:
    image: mongo:6.0.3
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth

