services:
  proxy:
    image: caddy:2.6.2
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./src-vue/dist:/dist
      - ./data/files:/data/files

  mongo:
    image: mongo:6.0.3
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    ports:
      - 27018:8081
