services:
  proxy:
    image: ghcr.io/fishhawk/wneg-proxy
    ports:
      - 80:80
    volumes:
      - ${DATA_PATH}/files:/data/files
    restart: always

  server:
    image: ghcr.io/fishhawk/wneg-server
    depends_on:
      - mongo
    environment:
      - HTTPS_PROXY
      - PIXIV_COOKIE_PHPSESSID
      - MONGODB_URL=mongodb://mongo:27017
    volumes:
      - ${DATA_PATH}/files:/data/files
    restart: always

  mongo:
    image: mongo:6.0.3
    volumes:
      - ${DATA_PATH}/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth
    restart: always

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    ports:
      - 27018:8081