services:
  proxy:
    image: ghcr.io/fishhawk/wneg-proxy
    ports:
      - 80:80
    volumes:
      - ${DATA_PATH}/files:/data/files
      - ${DATA_PATH}/files-extra:/data/files-extra
    restart: always

  server:
    image: ghcr.io/fishhawk/wneg-server
    depends_on:
      - mongo
    environment:
      - HTTPS_PROXY
      - EMAIL_PASSWORD
      - JWT_SECRET
      - PIXIV_COOKIE_PHPSESSID
      - MONGODB_URL=mongodb://mongo:27017
    ports:
      - 8081:8081
    volumes:
      - ${DATA_PATH}/files:/data/files
    restart: always

  mongo:
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_DATABASE=auth
    ports:
      - 27017:27017
    volumes:
      - ${DATA_PATH}/db:/data/db
    restart: always