services:
  proxy:
    image: ghcr.io/fishhawk/wneg-proxy

    ports:
      - 80:80
      - 443:443
    volumes:
      - ${BOOKS_PATH}:/books

    restart: always

  server:
    image: ghcr.io/fishhawk/wneg-server

    environment:
      - HTTPS_PROXY
      - PIXIV_COOKIE_PHPSESSID
    volumes:
      - ${BOOKS_PATH}:/books

    restart: always
    command: gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 120 'app:create_app()'
